s = set()
n = (input("Enter your number here1:"))
s.add(int(n))
n = (input("Enter your number here2 :"))
s.add(int(n))
n = (input("Enter your number here3:"))
s.add(int(n))
n = (input("Enter your number here4 :"))
s.add(int(n))
n = (input("Enter your number here 5 :"))
s.add(int(n))
n = (input("Enter your number here 6 :"))
s.add(int(n))
n = (input("Enter your number here 7 :"))
s.add(int(n))

print(s, type(s))